### ISSUE TITLE
Lag de un mes en valores devueltos por la función basket_goods?

### ISSUE THREAD

**Issue by Valerianus1** [calcita/ech#3]
Buenas. En primer lugar, muchas gracias por publicar esta paquete, es muy útil y ojalá más gente lo use.

No estoy del todo seguro que sea un bug, pero me sorprendió ver que el comando `basket_goods(year=2019)` devuelve valores con el rango de fechas dic-18 a nov-19. A menos que esté entendiendo mal y cada edición de la ECH incorpora datos de diciembre del año anterior, eso significaría que la función poverty calcula los niveles de pobreza en base a canastas del mes anterior al de la entrevista al hogar (por las dudas revisé si es la fecha y no el número que estaría mal asignado, pero la [serie de CBA y CBNA en la página del INE](https://www.ine.gub.uy/linea-de-pobreza) muestra valores para ene-19 que figuran en la segunda fila de `View(ech::basket_goods(year=2019))`  ).

Gracias y disculpen si en realidad es solo una confusión mía.

**Comment by calcita** [comment]
Hola @Valerianus1, nos alegra que te sea útil el paquete!

Respecto a la función basket_goods y otras  del paquete que se utilizan para convertir o comparar ingresos traen valores un mes rezagados. Este tiene sentido porque la medición de los ingresos en la ECH tiene un rezago de un mes (si el hogar fue encuestado, por ejemplo en marzo, en ese mes se preguntó por los ingresos del mes anterior, es decir, de febrero).

Espero haber aclarado el tema y aguardo tus comentarios.

**Comment by Valerianus1** [comment]
Perfecto, gracias @calcita 

Estos detalles que se pueden pasar por alto también hacen a la practicidad del paquete

Saludos
